### ISSUE TITLE
Still problems with arrowdesign

### ISSUE THREAD

**Issue by MaurizioLoreti** [akkana/gimp-plugins#19]
Hi there - I downloaded from the GIMP site gimp-3.0.0-RC1-arm64.dmg and installed the executable successfully; then:
- mkdir Library/Application\ Support/GIMP/3.0/plug-ins/arrowdesigner
* chmod 755 Library/Application\ Support/GIMP/3.0/plug-ins/arrowdesigner
* downloaded a fresh copy of arrowdesigner.py from your 3.0 repository and moved that file there
+ chmod 755 Library/Application\ Support/GIMP/3.0/plug-ins/arrowdesigner/arrowdesigner.py

When GIMP started, arrowdesigner did not show in the menus.  Running the file from a terminal, I got:

$ Library/Application\ Support/GIMP/3.0/plug-ins/arrowdesigner/arrowdesigner.py 
Traceback (most recent call last):
  File "/Users/loreti/Library/Application Support/GIMP/3.0/plug-ins/arrowdesigner/arrowdesigner.py", line 16, in <module>
    gi.require_version('Gimp', '3.0')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
$ python --version
Python 3.12.8
$

Sorry, but I don't speak python...  do you have a suggestion?

**Comment by akkana** [comment]
Sorry, GIMP changed its 3.0 API about a month ago, and I've managed to port a couple of my plug-ins (saver and blobipy) to the new API, but I haven't ported Arrow Designer yet. Thanks for the reminder: I will try to do that soon.

**Comment by akkana** [comment]
I've updated arrowdesigner for the latest GIMP3 API, and it should be working now. Let me know if you see any problems.
